name: Deploy to Cloud Run

# Defina quando o workflow será acionado. Exemplo: quando houver push na branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # (Opcional) Configure o Python e rode testes
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Rodar testes
        run: PYTHONPATH=. pytest tests/test_app.py  # Pré-adiciona o diretório atual ao PYTHONPATH
        working-directory: ${{ github.workspace }} # Garante que o diretório de trabalho é a raiz do repositório

      # Configura o Google Cloud SDK usando as credenciais e ID do projeto
      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ vars.GCP_SA_KEY }} # JSON do service account
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build da imagem usando Cloud Build (o Dockerfile precisa estar na raiz ou no local correto)
      - name: Build Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back

      # Deploy no Cloud Run, definindo as variáveis de ambiente
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy stark-back \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars PRIVATE_KEY="${{ vars.PRIVATE_KEY }}",STARKBANK_PROJECT_ID="${{ vars.STARKBANK_PROJECT_ID }}",TARGET_ACCOUNT="${{ vars.TARGET_ACCOUNT }}"