name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # Configure o Python e rode testes (mantido como no seu exemplo)
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Rodar testes
        run: PYTHONPATH=. pytest tests/test_app.py
        env:
          # Se seus testes precisarem dessas variáveis:
          PRIVATE_KEY: ${{ vars.PRIVATE_KEY }}
          STARKBANK_PROJECT_ID: ${{ vars.STARKBANK_PROJECT_ID }}
          TARGET_ACCOUNT: ${{ vars.TARGET_ACCOUNT }}

      # Configura o Google Cloud SDK (autentica e seleciona projeto)
      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          # Estes valores devem ser criados em Settings > Repository Variables
          service_account_key: ${{ vars.GCP_SA_KEY }}   # JSON da Service Account
          project_id: ${{ vars.GCP_PROJECT_ID }}
          export_default_credentials: true
          # install_components: cloud-run  <- REMOVED this line

      # Build da imagem no Cloud Build, usando seu Dockerfile
      - name: Build Docker image
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back \
            --project ${{ vars.GCP_PROJECT_ID }}

      # Deploy no Cloud Run, definindo as variáveis de ambiente
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy stark-back \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars PRIVATE_KEY="${{ vars.PRIVATE_KEY }}",STARKBANK_PROJECT_ID="${{ vars.STARKBANK_PROJECT_ID }}",TARGET_ACCOUNT="${{ vars.TARGET_ACCOUNT }}"