name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests
        # Se os testes precisam de variáveis de ambiente, injete-as:
        env:
          PRIVATE_KEY: ${{ vars.PRIVATE_KEY }}
          STARKBANK_PROJECT_ID: ${{ vars.STARKBANK_PROJECT_ID }}
          TARGET_ACCOUNT: ${{ vars.TARGET_ACCOUNT }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ vars.GCP_SA_KEY }}   # JSON da Service Account
          project_id: ${{ vars.GCP_PROJECT_ID }}
          export_default_credentials: true
          install_components: cloud-run

      - name: Build image with Cloud Build
        run: |
          # Agora o gcloud já está autenticado
          gcloud builds submit \
            --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy stark-back \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars PRIVATE_KEY="${{ vars.PRIVATE_KEY }}",STARKBANK_PROJECT_ID="${{ vars.STARKBANK_PROJECT_ID }}",TARGET_ACCOUNT="${{ vars.TARGET_ACCOUNT }}"
