name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Rodar testes
        run: PYTHONPATH=. pytest tests/test_app.py
        env:
          PRIVATE_KEY: ${{ vars.PRIVATE_KEY }}
          STARKBANK_PROJECT_ID: ${{ vars.STARKBANK_PROJECT_ID }}
          TARGET_ACCOUNT: ${{ vars.TARGET_ACCOUNT }}

      - name: Autenticar Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ vars.GCP_SA_KEY }}

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back \
            --project ${{ vars.GCP_PROJECT_ID }}

      - name: Gerar arquivo de variáveis de ambiente
        env:
          PRIVATE_KEY: ${{ vars.PRIVATE_KEY }}
          STARKBANK_PROJECT_ID: ${{ vars.STARKBANK_PROJECT_ID }}
          TARGET_ACCOUNT: ${{ vars.TARGET_ACCOUNT }}
        run: |
          PRIVATE_KEY_SINGLE_LINE=$(echo "$PRIVATE_KEY" | awk '{printf "%s\\n", $0}' | sed 's/\\n$//')
          {
            echo "PRIVATE_KEY: \"$PRIVATE_KEY_SINGLE_LINE\""
            echo "STARKBANK_PROJECT_ID: \"$STARKBANK_PROJECT_ID\""
            echo "TARGET_ACCOUNT: \"$TARGET_ACCOUNT\""
          } > env_vars.yaml

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy stark-back \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --env-vars-file env_vars.yaml