name: Deploy to Cloud Run

# Defina quando o workflow será acionado. Exemplo: quando houver push na branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # (Opcional) Configure o Python e rode testes
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Rodar testes
        run: PYTHONPATH=. pytest tests/test_app.py
        working-directory: ${{ github.workspace }}
        env: # Define environment variables for the test step
          PRIVATE_KEY: ${{ vars.PRIVATE_KEY }} # Provide the PRIVATE_KEY from GitHub Actions vars
          STARKBANK_PROJECT_ID: ${{ vars.STARKBANK_PROJECT_ID }} # If needed during import
          TARGET_ACCOUNT: ${{ vars.TARGET_ACCOUNT }} # If needed during import
          # Add other env vars if main.py needs them for initialization

      # Configura o Google Cloud SDK usando as credenciais e ID do projeto
      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ vars.GCP_SA_KEY }} # JSON do service account
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build da imagem usando Cloud Build (o Dockerfile precisa estar na raiz ou no local correto)
      - name: Build Docker image
        run: |
          gcloud auth activate-service-account --key-file=${{ runner.temp }}/gcloud-service-account.json # Explicitly activate the service account
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/stark-back --project ${{ secrets.GCP_PROJECT_ID }}

      # Deploy no Cloud Run, definindo as variáveis de ambiente
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy stark-back \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/stark-back \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars PRIVATE_KEY="${{ vars.PRIVATE_KEY }}",STARKBANK_PROJECT_ID="${{ vars.STARKBANK_PROJECT_ID }}",TARGET_ACCOUNT="${{ vars.TARGET_ACCOUNT }}"